/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceWorkspaceIdRouteRouteImport } from './routes/workspace/$workspaceId/route'
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from './routes/workspace/$workspaceId/index'
import { Route as WorkspaceWorkspaceIdCompaniesRouteImport } from './routes/workspace/$workspaceId/companies'
import { Route as WorkspaceWorkspaceIdContactsRouteImport } from './routes/workspace/$workspaceId/contacts'
import { Route as WorkspaceWorkspaceIdLeadsRouteImport } from './routes/workspace/$workspaceId/leads'
import { Route as WorkspaceWorkspaceIdTeamRouteImport } from './routes/workspace/$workspaceId/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRouteRoute =
  WorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdCompaniesRoute =
  WorkspaceWorkspaceIdCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdContactsRoute =
  WorkspaceWorkspaceIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdLeadsRoute =
  WorkspaceWorkspaceIdLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdTeamRoute =
  WorkspaceWorkspaceIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/set-password': typeof SetPasswordRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/companies': typeof WorkspaceWorkspaceIdCompaniesRoute
  '/workspace/$workspaceId/contacts': typeof WorkspaceWorkspaceIdContactsRoute
  '/workspace/$workspaceId/leads': typeof WorkspaceWorkspaceIdLeadsRoute
  '/workspace/$workspaceId/team': typeof WorkspaceWorkspaceIdTeamRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/set-password': typeof SetPasswordRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/companies': typeof WorkspaceWorkspaceIdCompaniesRoute
  '/workspace/$workspaceId/contacts': typeof WorkspaceWorkspaceIdContactsRoute
  '/workspace/$workspaceId/leads': typeof WorkspaceWorkspaceIdLeadsRoute
  '/workspace/$workspaceId/team': typeof WorkspaceWorkspaceIdTeamRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/set-password': typeof SetPasswordRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/companies': typeof WorkspaceWorkspaceIdCompaniesRoute
  '/workspace/$workspaceId/contacts': typeof WorkspaceWorkspaceIdContactsRoute
  '/workspace/$workspaceId/leads': typeof WorkspaceWorkspaceIdLeadsRoute
  '/workspace/$workspaceId/team': typeof WorkspaceWorkspaceIdTeamRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/set-password'
    | '/workspace/$workspaceId'
    | '/workspace/'
    | '/workspace/$workspaceId/companies'
    | '/workspace/$workspaceId/contacts'
    | '/workspace/$workspaceId/leads'
    | '/workspace/$workspaceId/team'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/set-password'
    | '/workspace'
    | '/workspace/$workspaceId/companies'
    | '/workspace/$workspaceId/contacts'
    | '/workspace/$workspaceId/leads'
    | '/workspace/$workspaceId/team'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/invite'
    | '/set-password'
    | '/workspace/$workspaceId'
    | '/workspace/'
    | '/workspace/$workspaceId/companies'
    | '/workspace/$workspaceId/contacts'
    | '/workspace/$workspaceId/leads'
    | '/workspace/$workspaceId/team'
    | '/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
  SetPasswordRoute: typeof SetPasswordRoute
  WorkspaceWorkspaceIdRouteRoute: typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/companies': {
      id: '/workspace/$workspaceId/companies'
      path: '/companies'
      fullPath: '/workspace/$workspaceId/companies'
      preLoaderRoute: typeof WorkspaceWorkspaceIdCompaniesRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/contacts': {
      id: '/workspace/$workspaceId/contacts'
      path: '/contacts'
      fullPath: '/workspace/$workspaceId/contacts'
      preLoaderRoute: typeof WorkspaceWorkspaceIdContactsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/leads': {
      id: '/workspace/$workspaceId/leads'
      path: '/leads'
      fullPath: '/workspace/$workspaceId/leads'
      preLoaderRoute: typeof WorkspaceWorkspaceIdLeadsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/team': {
      id: '/workspace/$workspaceId/team'
      path: '/team'
      fullPath: '/workspace/$workspaceId/team'
      preLoaderRoute: typeof WorkspaceWorkspaceIdTeamRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
  }
}

interface WorkspaceWorkspaceIdRouteRouteChildren {
  WorkspaceWorkspaceIdCompaniesRoute: typeof WorkspaceWorkspaceIdCompaniesRoute
  WorkspaceWorkspaceIdContactsRoute: typeof WorkspaceWorkspaceIdContactsRoute
  WorkspaceWorkspaceIdLeadsRoute: typeof WorkspaceWorkspaceIdLeadsRoute
  WorkspaceWorkspaceIdTeamRoute: typeof WorkspaceWorkspaceIdTeamRoute
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
}

const WorkspaceWorkspaceIdRouteRouteChildren: WorkspaceWorkspaceIdRouteRouteChildren =
  {
    WorkspaceWorkspaceIdCompaniesRoute: WorkspaceWorkspaceIdCompaniesRoute,
    WorkspaceWorkspaceIdContactsRoute: WorkspaceWorkspaceIdContactsRoute,
    WorkspaceWorkspaceIdLeadsRoute: WorkspaceWorkspaceIdLeadsRoute,
    WorkspaceWorkspaceIdTeamRoute: WorkspaceWorkspaceIdTeamRoute,
    WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  }

const WorkspaceWorkspaceIdRouteRouteWithChildren =
  WorkspaceWorkspaceIdRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
  SetPasswordRoute: SetPasswordRoute,
  WorkspaceWorkspaceIdRouteRoute: WorkspaceWorkspaceIdRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
